#ifndef _DIVAPOMELO_PREDEFINES_H_
#define _DIVAPOMELO_PREDEFINES_H_

#include "../PomeloCpp/PomeloCpp.h"
#include "../Lib/Base/Base.h"
#include "NetInfo.h"

namespace divapomelo {
	using namespace PomeloCpp;

	class PeerBase;
	class PeerComp;

	// Define Newwork Codes
	extern const char* EventCode[];
	extern const char* PlayerStatusCode[];

	enum EventEnum {
		ON_CONNECT = 0,
		ON_LOGIN,
		ON_CLOSE,
		ON_ENTER,
		ON_LEAVE,
		ON_CHAT,
		ON_KICK,
		ON_STAGE_SETMODE,
		ON_STAGE_SETHOOK,
		ON_STAGE_SETSONG,
		ON_STAGE_DRAW,
		ON_STAGE_READY,
		ON_STAGE_UNREADY,
		ON_STAGE_JOIN,
		ON_STAGE_LEAVE,
		ON_STAGE_CREATE,
		ON_STAGE_CLOSE,
		ON_STAGE_ALLINFO,
		ON_STAGE_START,
		ON_STAGE_RETURN,
		ON_STAGE_KICK,
		ON_GAME_START,
		ON_GAME_HEARTBEAT,
		ON_GAME_FAILURE,
		ON_GAME_RENEW,
		ON_GAME_RELAY_VOIDPERIOD,
		ON_GAME_RELAY_CHANGE,
		ON_GAME_RELAY_NEWPLAYER,
		PUSH_CHAT_SEND,
		PUSH_LOBBY_GETSTAGELIST,
		PUSH_LOBBY_CREATESTAGE,
		PUSH_LOBBY_JOINSTAGE,
		PUSH_LOBBY_LEAVESTAGE,
		PUSH_STAGE_DRAW,
		PUSH_STAGE_SETSONG,
		PUSH_STAGE_SETMODE,
		PUSH_STAGE_SETHOOK,
		PUSH_STAGE_READY,
		PUSH_STAGE_START,
		PUSH_STAGE_KICK,
		PUSH_GAME_BACK,
		PUSH_GAME_LINK,
		PUSH_GAME_UPDATE,
		PUSH_GAME_OVER,
		PUSH_GAME_EVAL,
		PUSH_GAME_FAILURE,
		PUSH_GAME_RENEW,
		PUSH_GAME_RELAY_IAMPLAYING,
		PUSH_GAME_RELAY_WANTTOCHANGE,
		PUSH_GAME_RELAY_WANTTOPLAY,
		LOCAL_UPDATE_SONG_UI
	};

	enum StageStateEnum {
		STAGE_STAT_IDLE = 0,
		STAGE_STAT_GAME
	};

	enum StageUserStateEnum {
		STAGE_USER_STAT_UNREADY = 0,
		STAGE_USER_STAT_READY,
		STAGE_UESR_STAT_PLAYING
	};

	enum GameStateEnum {
		GAME_STAT_LOAD = 0,
		GAME_STAT_PLAY,
		GAME_STAT_OVER,
		GAME_STAT_RETURN
	};
}

#endif