uniform float2 lightPoint;
const float sizeRatio = 16.0/9;
const float2 spotRadius = 0.4;

float4 main(float2 texCoord: TEXCOORD0,
                     uniform sampler2D decals: TEX0) : COLOR
{
   float4 col = tex2D(decals, texCoord);
   texCoord.x = lightPoint.x+(texCoord.x-lightPoint.x)*sizeRatio;
   float alpha = 1-distance(texCoord,lightPoint)/spotRadius;
   if(alpha<=0)
       col = float4(0,0,0,1);
   else
       col = col*alpha+float4(0,0,0,1)*(1-alpha);
   return col;
}
